dist: xenial
language: minimal
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - mesa-common-dev
      - libfreeimage-dev
      - libglew-dev
      - libsigc++-2.0-dev
      - libvorbis-dev
      - libassimp-dev
      - libsdl2-dev
      - libsdl2-image-dev
  homebrew:
    packages:
      - gcc
      - freetype
      - freeimage
      - glew
      - libsigc++@2
      - libvorbis
      - libpng
      - assimp
      - sdl2
      - sdl2_image
      - libogg
    update: true

matrix:
  include:
    - name: Build GCC
      os: linux

    - name: Build Clang
      os: linux
      env: CC=clang CXX=clang++

    - name: Build OSX
      os: osx

script:
  - ./bootstrap cmake && make -C build

before_deploy:
  - env SDL_VIDEODRIVER=dummy ./build/modelcompiler -b inplace
  - ./scripts/build-travis.sh

deploy:
  provider: releases
  api_key:
    secure: "Ajn9CykEp1CHKvIFmqYhP617A6cvZbsgHLw4VeDXeYob1aatUCAQXrjF9gUhbo4jwi2vtGFQyuK5TPHHHjSvk9EksW6c++qADqviAGvid6EAcG6AKuV76Nhx/IkCW0nUHk4ET2Zms3S2MON+rxUzihi4uCzuOlHUfG+5XntvL5Y="
  skip_cleanup: true
  file_glob: true
  file: release/zip/*
  on:
    repo: pioneerspacesim/pioneer
    tags: true
